Added validation in the field from
beijaflor-io/zenvia pull request #2
Opened 2017-03-10 18:18 UTC by kivervinicius

http://www.zenvia.com.br/desenvolvedores/sms/documentacao/documentos-antigos/api-legada-1-0/envio-de-sms-unico-http-webservice/

2017-03-10 18:24 UTC, yamadapc commented
Melhor validar tudo junto então:

>  Texto do SMS. Junto com o parâmetro “from”, deve ter no máximo 160 caracteres (140 para destinatários Nextel).

2017-03-10 18:27 UTC, kivervinicius commented
É verdade, vou ajustar aqui

2017-03-10 18:28 UTC, yamadapc commented
Seria:

`assert((message.from.length + ': '.length + message.msg.length) <= 20)`

2017-03-10 18:46 UTC, kivervinicius commented
Então mas olhando a documentação não é obrigatório o from o que acha de deixar livre?

2017-03-10 18:47 UTC, kivervinicius commented
Pensei em deixar assim:

`assert(message.msg.length <= 20, '`message.from` needs to be shorter or equal to 20 characters');
      assert((message.from.length + message.msg.length) <= 160, '`message.from` and `message.msg` summed must be greater than or equal to 160 characters.');`

2017-05-05 13:22 UTC, kivervinicius commented
O que acha da alteração? É possível fazer o merge?

2017-05-05 18:52 UTC, yamadapc requested changes
o que falamos e isso; posso adicionar quando parar, se quiser que entre o código muda seguindo isso e nossa última conversa; msg + from + 2 (': ') precisa ser menor que 160, from precisa ser menor que 20

2017-05-05 18:52 UTC, yamadapc commented on lib/index.js
> +      assert(message.msg.length <= 20, '`message.from` needs to be shorter or equal to 20 characters');
Hm... Isos aqui está errado, deveria ser `message.from.length`. Também tem as coisas que conversamos.

2017-05-05 19:03 UTC, kivervinicius commented on lib/index.js
> +      assert(message.msg.length <= 20, '`message.from` needs to be shorter or equal to 20 characters');
Tranquilo irei corrigir

2017-05-05 19:08 UTC, kivervinicius reviewed
Pronto, corrigido.

2017-05-05 19:48 UTC, yamadapc approved these changes

2017-05-05 19:48 UTC, merged

2017-05-05 19:49 UTC, yamadapc commented
Brigadíssimo! Publicado como `v1.0.4`. 🚀